<a href="https://colab.research.google.com/github/kerenG99/UFZ-Helmoltz-Summer-School-2026/blob/main/notebooks/03_data_wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 03 · Data wrangling with dplyr & tidyr

> **Trends in multi-omics data analysis for Microbial Ecology and Biotechnology** - Summer School, UFZ Leipzig  
> *Refreshing / Basic Knowledge: R* - Instructor: Anderson Santos

## Setup — run this first

This cell installs the R packages the lessons use and makes the example data available. On **Google Colab** it just works: run it (Shift+Enter) and wait until it prints **Ready**. You do not need to understand it.

In [1]:
# Setup — run this first. Works on Google Colab and on a local Jupyter with R.
# It installs the packages the lessons use and makes the example data available.

pkgs <- c("readr", "dplyr", "tidyr", "tibble", "ggplot2", "forcats", "stringr", "vegan")
to_install <- setdiff(pkgs, rownames(installed.packages()))
if (length(to_install) > 0) {
  # On Colab (Linux) use Posit Public Package Manager binaries: ~1-2 min instead of
  # compiling from source (~15-20 min).
  if (grepl("linux", R.version$os) && file.exists("/etc/os-release")) {
    cn <- grep("^VERSION_CODENAME=", readLines("/etc/os-release"), value = TRUE)
    cn <- gsub('VERSION_CODENAME=|"', "", cn)
    if (length(cn) == 1 && nzchar(cn)) {
      options(repos = c(CRAN = sprintf("https://p3m.dev/cran/__linux__/%s/latest", cn)))
      options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(),
              paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))
    }
  }
  install.packages(to_install)
}

# Fetch the example data if it is not already next to the notebook (the Colab case).
if (!file.exists("../data/sample_metadata.csv") && !file.exists("data/sample_metadata.csv")) {
  system("git clone -q https://github.com/andersonavilasantos/ufz-summerschool-r.git course_repo")
  setwd("course_repo/notebooks")
}

# Load the packages quietly and keep read_csv output tidy (cleaner notebook output).
suppressPackageStartupMessages(invisible(lapply(pkgs, require, character.only = TRUE)))
options(readr.show_col_types = FALSE)

cat("Ready. Data folder:", if (file.exists("../data/sample_metadata.csv")) "../data" else "data", "\n")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘permute’

Ready. Data folder: ../data

## Learning objectives

This is the **core** of the session — the toolkit you will reuse all week.

- Master the six core **dplyr verbs**: `filter`, `select`, `mutate`, `arrange`,
  `summarise`, and `group_by`.
- Combine tables with **joins** (`left_join`).
- Move between **wide** and **long** shapes with `pivot_longer` / `pivot_wider`.
- Tidy text and factors with **stringr** and **forcats** along the way.
- Put it together to compute a real result: **taxonomic composition per region**.

---

## 0 · Setup

In [2]:
library(readr)     # read_csv: import the CSVs
library(dplyr)     # the wrangling verbs (filter, select, mutate, group_by, …)
library(tidyr)     # reshape wide <-> long (pivot_longer / pivot_wider)
library(stringr)   # tidy text columns (str_*)
library(forcats)   # reorder/relabel factors (fct_*)

# Pick the data folder that exists, so the lesson runs from notebooks/ or the root.
data_dir <- if (file.exists("../data/sample_metadata.csv")) "../data" else "data"

# Load the three linked tables of our HITChip study.
meta     <- read_csv(file.path(data_dir, "sample_metadata.csv"))  # one row per sample
taxonomy <- read_csv(file.path(data_dir, "taxonomy.csv"))         # genus -> phylum/family
abund    <- read_csv(file.path(data_dir, "genus_abundance.csv"))  # sample x 130 genera

# Re-impose the clinical BMI order once (as in lesson 02), so every group_by respects it.
bmi_levels <- c("underweight","lean","overweight","obese","severeobese","morbidobese")
meta <- meta |> mutate(bmi_group = factor(bmi_group, levels = bmi_levels))

glimpse(meta)      # quick check: columns, types, first values

Rows: 1,006
Columns: 7
$ sample_id         <chr> "Sample-1", "Sample-2", "Sample-3", "Sample-4", "Sam…
$ subject_id        <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1…
$ age               <dbl> 28, 24, 52, 22, 25, 42, 25, 27, 21, 25, 54, NA, NA, …
$ sex               <chr> "male", "female", "male", "female", "female", "male"…
$ nationality       <chr> "US", "US", "US", "US", "US", "US", "US", "US", "US"…
$ bmi_group         <fct> severeobese, obese, lean, underweight, lean, lean, u…
$ diversity_shannon <dbl> 5.76, 6.06, 5.50, 5.87, 5.89, 5.53, 5.49, 5.38, 5.34…

---

## 1 · `filter()` — keep the rows you want

`filter()` keeps rows that meet a condition. Conditions use `==`, `>`, `<`, `>=`,
`!=`, and combine with `&` (and), `|` (or).

In [5]:
# Keep only rows where nationality equals "Scandinavia" ('==' tests equality).
meta |> filter(nationality == "Scandinavia")

# Multiple conditions separated by a comma are combined with "and" (both must hold).
meta |> filter(bmi_group == "lean", age > 50)   # lean and older than 50

# Pipe the filtered rows into nrow() to just count them, not print them.
meta |> filter(diversity_shannon > 6) |> nrow() # how many high-diversity samples?

    sample_id  subject_id age sex    nationality bmi_group   diversity_shannon
1   Sample-39   39        56  male   Scandinavia overweight  5.72
2   Sample-40   40        39  female Scandinavia lean        5.88
3   Sample-41   41        38  female Scandinavia underweight 5.64
4   Sample-42   42        53  male   Scandinavia lean        6.00
5   Sample-43   43        42  female Scandinavia overweight  6.05
6   Sample-217 217        42  female Scandinavia obese       5.60
7   Sample-218 218        34  male   Scandinavia obese       5.73
8   Sample-219 219        40  female Scandinavia severeobese 6.12
9   Sample-220 220        61  male   Scandinavia obese       5.95
10  Sample-221 221        46  female Scandinavia severeobese 5.84
11  Sample-222 222        52  female Scandinavia obese       5.73
12  Sample-223 223        38  female Scandinavia severeobese 5.27
13  Sample-224 224        59  female Scandinavia obese       5.74
14  Sample-225 225        49  female Scandinavia obese       5.80
15  Sample-226 226        60  female Scandinavia obese       5.80
16  Sample-227 227        45  female Scandinavia severeobese 5.72
17  Sample-228 228        53  female Scandinavia severeobese 5.74
18  Sample-229 229        56  male   Scandinavia severeobese 5.76
19  Sample-230 230        61  female Scandinavia obese       6.12
20  Sample-231 231        55  female Scandinavia obese       5.60
21  Sample-232 232        32  male   Scandinavia obese       5.64
22  Sample-233 233        45  female Scandinavia obese       6.10
23  Sample-234 234        54  female Scandinavia obese       5.95
24  Sample-235 235        56  female Scandinavia obese       5.85
25  Sample-236 236        56  male   Scandinavia obese       5.76
26  Sample-237 237        40  female Scandinavia obese       6.00
27  Sample-238 238        58  female Scandinavia severeobese 5.70
28  Sample-239 239        63  male   Scandinavia overweight  5.85
29  Sample-240 240        55  female Scandinavia severeobese 6.09
30  Sample-241 241        42  female Scandinavia severeobese 5.89
⋮   ⋮          ⋮          ⋮   ⋮      ⋮           ⋮           ⋮
133 Sample-879 879        NA  NA     Scandinavia NA          5.65
134 Sample-880 880        NA  NA     Scandinavia NA          5.52
135 Sample-881 881        NA  NA     Scandinavia NA          5.67
136 Sample-882 882        NA  NA     Scandinavia NA          5.67
137 Sample-883 883        NA  NA     Scandinavia NA          5.85
138 Sample-884 884        NA  NA     Scandinavia NA          5.80
139 Sample-885 885        29  female Scandinavia NA          5.61
140 Sample-886 886        37  female Scandinavia NA          5.67
141 Sample-887 887        36  female Scandinavia NA          4.89
142 Sample-888 888        27  female Scandinavia NA          5.56
143 Sample-889 889        28  female Scandinavia NA          5.57
144 Sample-890 890        35  female Scandinavia NA          5.97
145 Sample-891 891        25  female Scandinavia NA          5.56
146 Sample-892 892        28  female Scandinavia NA          5.89
147 Sample-893 893        28  female Scandinavia NA          5.81
148 Sample-894 894        29  female Scandinavia NA          5.38
149 Sample-895 895        46  female Scandinavia overweight  5.80
150 Sample-896 896        47  female Scandinavia lean        5.99
151 Sample-897 897        40  female Scandinavia lean        5.49
152 Sample-898 898        58  female Scandinavia overweight  5.83
153 Sample-899 899        39  female Scandinavia lean        5.73
154 Sample-900 900        24  female Scandinavia lean        5.55
155 Sample-901 901        19  female Scandinavia underweight 5.58
156 Sample-902 902        45  female Scandinavia lean        5.81
157 Sample-903 903        57  female Scandinavia lean        6.05
158 Sample-904 904        58  female Scandinavia lean        5.75
159 Sample-905 905        57  female Scandinavia lean        5.77
160 Sample-906 906        53  female Scandinavia lean        5.81
161 Sample-991 991        41  female Scandinavia lean        6.07
162 Sample-992 992        35  female Scandinavia lean        5.97

    sample_id  subject_id age sex    nationality bmi_group   diversity_shannon
1   Sample-39   39        56  male   Scandinavia overweight  5.72
2   Sample-40   40        39  female Scandinavia lean        5.88
3   Sample-41   41        38  female Scandinavia underweight 5.64
4   Sample-42   42        53  male   Scandinavia lean        6.00
5   Sample-43   43        42  female Scandinavia overweight  6.05
6   Sample-217 217        42  female Scandinavia obese       5.60
7   Sample-218 218        34  male   Scandinavia obese       5.73
8   Sample-219 219        40  female Scandinavia severeobese 6.12
9   Sample-220 220        61  male   Scandinavia obese       5.95
10  Sample-221 221        46  female Scandinavia severeobese 5.84
11  Sample-222 222        52  female Scandinavia obese       5.73
12  Sample-223 223        38  female Scandinavia severeobese 5.27
13  Sample-224 224        59  female Scandinavia obese       5.74
14  Sample-225 225        49  female Scandinavia obese       5.80
15  Sample-226 226        60  female Scandinavia obese       5.80
16  Sample-227 227        45  female Scandinavia severeobese 5.72
17  Sample-228 228        53  female Scandinavia severeobese 5.74
18  Sample-229 229        56  male   Scandinavia severeobese 5.76
19  Sample-230 230        61  female Scandinavia obese       6.12
20  Sample-231 231        55  female Scandinavia obese       5.60
21  Sample-232 232        32  male   Scandinavia obese       5.64
22  Sample-233 233        45  female Scandinavia obese       6.10
23  Sample-234 234        54  female Scandinavia obese       5.95
24  Sample-235 235        56  female Scandinavia obese       5.85
25  Sample-236 236        56  male   Scandinavia obese       5.76
26  Sample-237 237        40  female Scandinavia obese       6.00
27  Sample-238 238        58  female Scandinavia severeobese 5.70
28  Sample-239 239        63  male   Scandinavia overweight  5.85
29  Sample-240 240        55  female Scandinavia severeobese 6.09
30  Sample-241 241        42  female Scandinavia severeobese 5.89
⋮   ⋮          ⋮          ⋮   ⋮      ⋮           ⋮           ⋮
133 Sample-879 879        NA  NA     Scandinavia NA          5.65
134 Sample-880 880        NA  NA     Scandinavia NA          5.52
135 Sample-881 881        NA  NA     Scandinavia NA          5.67
136 Sample-882 882        NA  NA     Scandinavia NA          5.67
137 Sample-883 883        NA  NA     Scandinavia NA          5.85
138 Sample-884 884        NA  NA     Scandinavia NA          5.80
139 Sample-885 885        29  female Scandinavia NA          5.61
140 Sample-886 886        37  female Scandinavia NA          5.67
141 Sample-887 887        36  female Scandinavia NA          4.89
142 Sample-888 888        27  female Scandinavia NA          5.56
143 Sample-889 889        28  female Scandinavia NA          5.57
144 Sample-890 890        35  female Scandinavia NA          5.97
145 Sample-891 891        25  female Scandinavia NA          5.56
146 Sample-892 892        28  female Scandinavia NA          5.89
147 Sample-893 893        28  female Scandinavia NA          5.81
148 Sample-894 894        29  female Scandinavia NA          5.38
149 Sample-895 895        46  female Scandinavia overweight  5.80
150 Sample-896 896        47  female Scandinavia lean        5.99
151 Sample-897 897        40  female Scandinavia lean        5.49
152 Sample-898 898        58  female Scandinavia overweight  5.83
153 Sample-899 899        39  female Scandinavia lean        5.73
154 Sample-900 900        24  female Scandinavia lean        5.55
155 Sample-901 901        19  female Scandinavia underweight 5.58
156 Sample-902 902        45  female Scandinavia lean        5.81
157 Sample-903 903        57  female Scandinavia lean        6.05
158 Sample-904 904        58  female Scandinavia lean        5.75
159 Sample-905 905        57  female Scandinavia lean        5.77
160 Sample-906 906        53  female Scandinavia lean        5.81
161 Sample-991 991        41  female Scandinavia lean        6.07
162 Sample-992 992        35  female Scandinavia lean        5.97

    sample_id  subject_id age sex    nationality   bmi_group diversity_shannon
1   Sample-3     3        52  male   US            lean      5.50
2   Sample-21   21        60  female US            lean      5.72
3   Sample-26   26        54  female US            lean      5.82
4   Sample-42   42        53  male   Scandinavia   lean      6.00
5   Sample-70   70        77  male   SouthEurope   lean      5.97
6   Sample-71   71        60  female SouthEurope   lean      6.23
7   Sample-73   73        74  female SouthEurope   lean      5.92
8   Sample-78   78        70  male   SouthEurope   lean      5.98
9   Sample-80   80        76  male   SouthEurope   lean      6.08
10  Sample-82   82        63  female SouthEurope   lean      5.70
11  Sample-84   84        76  male   SouthEurope   lean      5.82
12  Sample-87   87        67  male   SouthEurope   lean      6.00
13  Sample-106 106        52  female CentralEurope lean      6.11
14  Sample-108 108        55  male   CentralEurope lean      6.08
15  Sample-109 109        58  female CentralEurope lean      5.98
16  Sample-110 110        65  male   CentralEurope lean      6.02
17  Sample-111 111        52  female CentralEurope lean      5.87
18  Sample-115 115        54  male   CentralEurope lean      6.03
19  Sample-117 117        60  female CentralEurope lean      5.88
20  Sample-118 118        52  female CentralEurope lean      6.11
21  Sample-120 120        56  male   CentralEurope lean      6.07
22  Sample-121 121        52  female CentralEurope lean      6.11
23  Sample-122 122        59  female CentralEurope lean      6.12
24  Sample-128 128        64  male   CentralEurope lean      5.94
25  Sample-129 129        58  female CentralEurope lean      5.95
26  Sample-130 130        60  female CentralEurope lean      6.03
27  Sample-133 133        53  female CentralEurope lean      6.02
28  Sample-135 135        58  female CentralEurope lean      5.99
29  Sample-136 136        51  female CentralEurope lean      6.18
30  Sample-178 178        52  male   CentralEurope lean      6.19
⋮   ⋮          ⋮          ⋮   ⋮      ⋮             ⋮         ⋮
100 Sample-664 664        62  female CentralEurope lean      5.69
101 Sample-665 665        62  female CentralEurope lean      5.78
102 Sample-672 672        57  male   CentralEurope lean      5.81
103 Sample-674 674        72  female CentralEurope lean      6.07
104 Sample-677 677        57  female CentralEurope lean      5.74
105 Sample-678 678        52  female CentralEurope lean      5.96
106 Sample-679 679        52  male   CentralEurope lean      6.07
107 Sample-685 685        62  female CentralEurope lean      5.90
108 Sample-688 688        61  female CentralEurope lean      5.95
109 Sample-693 693        61  male   CentralEurope lean      6.22
110 Sample-696 696        61  male   CentralEurope lean      5.96
111 Sample-740 740        53  male   US            lean      5.43
112 Sample-747 747        51  male   US            lean      5.93
113 Sample-750 750        55  male   Scandinavia   lean      6.08
114 Sample-772 772        52  female Scandinavia   lean      6.07
115 Sample-778 778        53  female Scandinavia   lean      5.89
116 Sample-784 784        54  female Scandinavia   lean      5.71
117 Sample-792 792        53  female Scandinavia   lean      6.11
118 Sample-793 793        55  male   Scandinavia   lean      5.87
119 Sample-800 800        52  female Scandinavia   lean      6.04
120 Sample-808 808        55  male   Scandinavia   lean      5.98
121 Sample-817 817        52  male   Scandinavia   lean      6.21
122 Sample-821 821        53  female Scandinavia   lean      5.90
123 Sample-823 823        55  male   Scandinavia   lean      6.13
124 Sample-828 828        51  male   Scandinavia   lean      6.17
125 Sample-837 837        53  female Scandinavia   lean      5.96
126 Sample-903 903        57  female Scandinavia   lean      6.05
127 Sample-904 904        58  female Scandinavia   lean      5.75
128 Sample-905 905        57  female Scandinavia   lean      5.77
129 Sample-906 906        53  female Scandinavia   lean      5.81

[1] 250

Two very common needs: dropping missing values and matching a **set** of values.

In [7]:
meta |> filter(!is.na(age)) |> nrow()              # '!is.na(age)' = keep rows where age is known
meta |> filter(nationality %in% c("US", "UKIE"))   # '%in%' = value is one of this set

[1] 950

   sample_id   subject_id age sex    nationality bmi_group   diversity_shannon
1  Sample-1     1         28  male   US          severeobese 5.76
2  Sample-2     2         24  female US          obese       6.06
3  Sample-3     3         52  male   US          lean        5.50
4  Sample-4     4         22  female US          underweight 5.87
5  Sample-5     5         25  female US          lean        5.89
6  Sample-6     6         42  male   US          lean        5.53
7  Sample-7     7         25  female US          underweight 5.49
8  Sample-8     8         27  female US          lean        5.38
9  Sample-9     9         21  female US          lean        5.34
10 Sample-10   10         25  female US          lean        5.64
11 Sample-11   11         54  female US          underweight 5.57
12 Sample-12   12         NA  NA     US          NA          5.28
13 Sample-13   13         NA  NA     US          NA          5.86
14 Sample-14   14         NA  NA     US          NA          5.81
15 Sample-15   15         58  female US          obese       5.40
16 Sample-16   16         33  female US          severeobese 5.51
17 Sample-17   17         28  female US          lean        5.55
18 Sample-18   18         23  female US          lean        5.47
19 Sample-19   19         37  female US          lean        5.75
20 Sample-20   20         37  female US          lean        5.87
21 Sample-21   21         60  female US          lean        5.72
22 Sample-22   22         28  female US          lean        5.39
23 Sample-23   23         52  female US          overweight  5.95
24 Sample-24   24         22  female US          lean        6.09
25 Sample-25   25         21  male   US          NA          5.97
26 Sample-26   26         54  female US          lean        5.82
27 Sample-33   33         NA  NA     US          NA          5.29
28 Sample-34   34         NA  NA     US          NA          5.51
29 Sample-35   35         NA  NA     US          NA          5.45
30 Sample-36   36         NA  NA     US          NA          5.03
⋮  ⋮           ⋮          ⋮   ⋮      ⋮           ⋮           ⋮
65 Sample-852   852       26  male   UKIE        overweight  5.77
66 Sample-853   853       22  male   UKIE        lean        5.94
67 Sample-854   854       25  male   UKIE        lean        5.79
68 Sample-855   855       28  male   UKIE        lean        6.04
69 Sample-856   856       29  male   UKIE        lean        6.00
70 Sample-857   857       21  female UKIE        lean        5.79
71 Sample-858   858       23  female UKIE        lean        6.06
72 Sample-859   859       24  female UKIE        lean        6.01
73 Sample-860   860       26  male   UKIE        overweight  5.84
74 Sample-861   861       21  male   UKIE        lean        5.90
75 Sample-862   862       21  male   UKIE        lean        5.92
76 Sample-863   863       36  female UKIE        lean        5.93
77 Sample-864   864       39  female UKIE        overweight  5.94
78 Sample-865   865       19  female UKIE        lean        5.59
79 Sample-866   866       21  male   UKIE        overweight  5.89
80 Sample-867   867       33  male   UKIE        overweight  5.97
81 Sample-868   868       26  male   UKIE        lean        5.67
82 Sample-994   994       33  male   UKIE        overweight  5.67
83 Sample-995   995       43  female UKIE        overweight  5.58
84 Sample-996   996       36  male   UKIE        overweight  5.77
85 Sample-997   997       31  male   UKIE        overweight  5.59
86 Sample-998   998       25  female UKIE        overweight  6.05
87 Sample-999   999       37  male   UKIE        lean        5.85
88 Sample-1000 1000       26  male   UKIE        overweight  5.71
89 Sample-1001 1001       20  male   UKIE        lean        6.07
90 Sample-1002 1002       40  male   UKIE        lean        5.87
91 Sample-1003 1003       26  female UKIE        severeobese 6.02
92 Sample-1004 1004       45  male   UKIE        lean        5.85
93 Sample-1005 1005       26  male   UKIE        overweight  5.71
94 Sample-1006 1006       23  female UKIE        lean        6.07

[1] 950

[1] 950

### Exercise 1

Keep only participants who are **female**, from **CentralEurope**, and whose
`age` is known. How many are there?

<details><summary><b>Solution</b> (click to expand)</summary>


```r
meta |>
  filter(sex == "female", nationality == "CentralEurope", !is.na(age)) |>
  nrow()
```
</details>

In [10]:
#editing the entire dataset to the arguements
meta |>
  filter(sex == "female", nationality == "CentralEurope", !is.na(age)) |>
  nrow()
meta2 <- meta |>
  filter(sex == "female", nationality == "CentralEurope", !is.na(age)) #removing nrow gives out the table summary
meta2

[1] 343

    sample_id  subject_id age sex    nationality   bmi_group
1   Sample-106 106        52  female CentralEurope lean
2   Sample-107 107        21  female CentralEurope lean
3   Sample-109 109        58  female CentralEurope lean
4   Sample-111 111        52  female CentralEurope lean
5   Sample-113 113        50  female CentralEurope lean
6   Sample-116 116        23  female CentralEurope lean
7   Sample-117 117        60  female CentralEurope lean
8   Sample-118 118        52  female CentralEurope lean
9   Sample-119 119        46  female CentralEurope overweight
10  Sample-121 121        52  female CentralEurope lean
11  Sample-122 122        59  female CentralEurope lean
12  Sample-123 123        26  female CentralEurope underweight
13  Sample-125 125        23  female CentralEurope lean
14  Sample-126 126        50  female CentralEurope lean
15  Sample-129 129        58  female CentralEurope lean
16  Sample-130 130        60  female CentralEurope lean
17  Sample-131 131        52  female CentralEurope NA
18  Sample-132 132        27  female CentralEurope lean
19  Sample-133 133        53  female CentralEurope lean
20  Sample-135 135        58  female CentralEurope lean
21  Sample-136 136        51  female CentralEurope lean
22  Sample-137 137        25  female CentralEurope lean
23  Sample-138 138        30  female CentralEurope lean
24  Sample-139 139        21  female CentralEurope lean
25  Sample-141 141        31  female CentralEurope lean
26  Sample-142 142        65  female CentralEurope obese
27  Sample-143 143        58  female CentralEurope overweight
28  Sample-144 144        49  female CentralEurope lean
29  Sample-146 146        62  female CentralEurope overweight
30  Sample-148 148        23  female CentralEurope lean
⋮   ⋮          ⋮          ⋮   ⋮      ⋮             ⋮
314 Sample-941 941        35  female CentralEurope lean
315 Sample-942 942        35  female CentralEurope lean
316 Sample-943 943        33  female CentralEurope obese
317 Sample-944 944        33  female CentralEurope obese
318 Sample-946 946        33  female CentralEurope lean
319 Sample-947 947        33  female CentralEurope lean
320 Sample-948 948        33  female CentralEurope overweight
321 Sample-949 949        33  female CentralEurope lean
322 Sample-950 950        33  female CentralEurope lean
323 Sample-951 951        33  female CentralEurope lean
324 Sample-952 952        33  female CentralEurope lean
325 Sample-953 953        32  female CentralEurope lean
326 Sample-954 954        32  female CentralEurope lean
327 Sample-955 955        32  female CentralEurope lean
328 Sample-956 956        32  female CentralEurope lean
329 Sample-957 957        30  female CentralEurope lean
330 Sample-958 958        30  female CentralEurope lean
331 Sample-961 961        30  female CentralEurope overweight
332 Sample-962 962        30  female CentralEurope lean
333 Sample-963 963        28  female CentralEurope lean
334 Sample-964 964        28  female CentralEurope overweight
335 Sample-965 965        25  female CentralEurope lean
336 Sample-966 966        25  female CentralEurope lean
337 Sample-967 967        25  female CentralEurope lean
338 Sample-968 968        25  female CentralEurope lean
339 Sample-975 975        22  female CentralEurope lean
340 Sample-976 976        22  female CentralEurope lean
341 Sample-977 977        21  female CentralEurope lean
342 Sample-978 978        21  female CentralEurope lean
343 Sample-993 993        26  female CentralEurope lean
    diversity_shannon
1   6.11
2   5.97
3   5.98
4   5.87
5   5.97
6   5.90
7   5.88
8   6.11
9   5.96
10  6.11
11  6.12
12  5.53
13  5.96
14  5.84
15  5.95
16  6.03
17  6.04
18  5.72
19  6.02
20  5.99
21  6.18
22  6.13
23  6.11
24  6.05
25  5.88
26  6.03
27  5.89
28  5.63
29  6.02
30  6.22
⋮   ⋮
314 5.46
315 5.36
316 6.00
317 5.91
318 5.73
319 6.07
320 5.89
321 5.87
322 5.30
323 5.61
324 5.95
325 5.49
326 5.93
327 6.12
328 6.07
329 5.76
330 5.67
331 5.64
332 5.84
333 5.94
334 5.82
335 5.51
336 5.65
337 6.20
338 5.98
339 4.82
340 5.41
341 5.89
342 6.03
343 6.00

---

## 2 · `select()` — keep the columns you want

In [11]:
#only getting specifics columns
meta |> select(sample_id, age, bmi_group)      # keep only these three columns, in this order
meta |> select(-subject_id)                    # a leading '-' drops a column, keep the rest
meta |> select(sample_id, starts_with("div"))  # starts_with(): match columns by name prefix

     sample_id   age bmi_group
1    Sample-1    28  severeobese
2    Sample-2    24  obese
3    Sample-3    52  lean
4    Sample-4    22  underweight
5    Sample-5    25  lean
6    Sample-6    42  lean
7    Sample-7    25  underweight
8    Sample-8    27  lean
9    Sample-9    21  lean
10   Sample-10   25  lean
11   Sample-11   54  underweight
12   Sample-12   NA  NA
13   Sample-13   NA  NA
14   Sample-14   NA  NA
15   Sample-15   58  obese
16   Sample-16   33  severeobese
17   Sample-17   28  lean
18   Sample-18   23  lean
19   Sample-19   37  lean
20   Sample-20   37  lean
21   Sample-21   60  lean
22   Sample-22   28  lean
23   Sample-23   52  overweight
24   Sample-24   22  lean
25   Sample-25   21  NA
26   Sample-26   54  lean
27   Sample-27   33  severeobese
28   Sample-28   39  severeobese
29   Sample-29   36  severeobese
30   Sample-30   50  severeobese
⋮    ⋮           ⋮   ⋮
977  Sample-977  21  lean
978  Sample-978  21  lean
979  Sample-979  19  lean
980  Sample-980  19  overweight
981  Sample-981  23  lean
982  Sample-982  19  overweight
983  Sample-983  19  lean
984  Sample-984  26  overweight
985  Sample-985  25  lean
986  Sample-986  30  lean
987  Sample-987  52  overweight
988  Sample-988  24  lean
989  Sample-989  38  lean
990  Sample-990  42  overweight
991  Sample-991  41  lean
992  Sample-992  35  lean
993  Sample-993  26  lean
994  Sample-994  33  overweight
995  Sample-995  43  overweight
996  Sample-996  36  overweight
997  Sample-997  31  overweight
998  Sample-998  25  overweight
999  Sample-999  37  lean
1000 Sample-1000 26  overweight
1001 Sample-1001 20  lean
1002 Sample-1002 40  lean
1003 Sample-1003 26  severeobese
1004 Sample-1004 45  lean
1005 Sample-1005 26  overweight
1006 Sample-1006 23  lean

     sample_id   age sex    nationality   bmi_group   diversity_shannon
1    Sample-1    28  male   US            severeobese 5.76
2    Sample-2    24  female US            obese       6.06
3    Sample-3    52  male   US            lean        5.50
4    Sample-4    22  female US            underweight 5.87
5    Sample-5    25  female US            lean        5.89
6    Sample-6    42  male   US            lean        5.53
7    Sample-7    25  female US            underweight 5.49
8    Sample-8    27  female US            lean        5.38
9    Sample-9    21  female US            lean        5.34
10   Sample-10   25  female US            lean        5.64
11   Sample-11   54  female US            underweight 5.57
12   Sample-12   NA  NA     US            NA          5.28
13   Sample-13   NA  NA     US            NA          5.86
14   Sample-14   NA  NA     US            NA          5.81
15   Sample-15   58  female US            obese       5.40
16   Sample-16   33  female US            severeobese 5.51
17   Sample-17   28  female US            lean        5.55
18   Sample-18   23  female US            lean        5.47
19   Sample-19   37  female US            lean        5.75
20   Sample-20   37  female US            lean        5.87
21   Sample-21   60  female US            lean        5.72
22   Sample-22   28  female US            lean        5.39
23   Sample-23   52  female US            overweight  5.95
24   Sample-24   22  female US            lean        6.09
25   Sample-25   21  male   US            NA          5.97
26   Sample-26   54  female US            lean        5.82
27   Sample-27   33  male   CentralEurope severeobese 5.53
28   Sample-28   39  male   CentralEurope severeobese 5.87
29   Sample-29   36  male   CentralEurope severeobese 5.70
30   Sample-30   50  male   CentralEurope severeobese 5.59
⋮    ⋮           ⋮   ⋮      ⋮             ⋮           ⋮
977  Sample-977  21  female CentralEurope lean        5.89
978  Sample-978  21  female CentralEurope lean        6.03
979  Sample-979  19  male   CentralEurope lean        6.27
980  Sample-980  19  male   CentralEurope overweight  5.78
981  Sample-981  23  male   CentralEurope lean        5.78
982  Sample-982  19  male   CentralEurope overweight  5.59
983  Sample-983  19  male   CentralEurope lean        5.66
984  Sample-984  26  male   NA            overweight  5.65
985  Sample-985  25  male   NA            lean        6.13
986  Sample-986  30  female NA            lean        6.01
987  Sample-987  52  male   NA            overweight  5.68
988  Sample-988  24  female NA            lean        5.85
989  Sample-989  38  male   NA            lean        5.91
990  Sample-990  42  female NA            overweight  5.57
991  Sample-991  41  female Scandinavia   lean        6.07
992  Sample-992  35  female Scandinavia   lean        5.97
993  Sample-993  26  female CentralEurope lean        6.00
994  Sample-994  33  male   UKIE          overweight  5.67
995  Sample-995  43  female UKIE          overweight  5.58
996  Sample-996  36  male   UKIE          overweight  5.77
997  Sample-997  31  male   UKIE          overweight  5.59
998  Sample-998  25  female UKIE          overweight  6.05
999  Sample-999  37  male   UKIE          lean        5.85
1000 Sample-1000 26  male   UKIE          overweight  5.71
1001 Sample-1001 20  male   UKIE          lean        6.07
1002 Sample-1002 40  male   UKIE          lean        5.87
1003 Sample-1003 26  female UKIE          severeobese 6.02
1004 Sample-1004 45  male   UKIE          lean        5.85
1005 Sample-1005 26  male   UKIE          overweight  5.71
1006 Sample-1006 23  female UKIE          lean        6.07

     sample_id   diversity_shannon
1    Sample-1    5.76
2    Sample-2    6.06
3    Sample-3    5.50
4    Sample-4    5.87
5    Sample-5    5.89
6    Sample-6    5.53
7    Sample-7    5.49
8    Sample-8    5.38
9    Sample-9    5.34
10   Sample-10   5.64
11   Sample-11   5.57
12   Sample-12   5.28
13   Sample-13   5.86
14   Sample-14   5.81
15   Sample-15   5.40
16   Sample-16   5.51
17   Sample-17   5.55
18   Sample-18   5.47
19   Sample-19   5.75
20   Sample-20   5.87
21   Sample-21   5.72
22   Sample-22   5.39
23   Sample-23   5.95
24   Sample-24   6.09
25   Sample-25   5.97
26   Sample-26   5.82
27   Sample-27   5.53
28   Sample-28   5.87
29   Sample-29   5.70
30   Sample-30   5.59
⋮    ⋮           ⋮
977  Sample-977  5.89
978  Sample-978  6.03
979  Sample-979  6.27
980  Sample-980  5.78
981  Sample-981  5.78
982  Sample-982  5.59
983  Sample-983  5.66
984  Sample-984  5.65
985  Sample-985  6.13
986  Sample-986  6.01
987  Sample-987  5.68
988  Sample-988  5.85
989  Sample-989  5.91
990  Sample-990  5.57
991  Sample-991  6.07
992  Sample-992  5.97
993  Sample-993  6.00
994  Sample-994  5.67
995  Sample-995  5.58
996  Sample-996  5.77
997  Sample-997  5.59
998  Sample-998  6.05
999  Sample-999  5.85
1000 Sample-1000 5.71
1001 Sample-1001 6.07
1002 Sample-1002 5.87
1003 Sample-1003 6.02
1004 Sample-1004 5.85
1005 Sample-1005 5.71
1006 Sample-1006 6.07

`rename()` changes a column name (`new = old`):

In [12]:
meta |> rename(shannon = diversity_shannon) |> names()  # rename(new = old); names() confirms it

[1] "sample_id"   "subject_id"  "age"         "sex"         "nationality"
[6] "bmi_group"   "shannon"

In [14]:
meta |> rename(subject = subject_id) |> names() #new = old, names is colomun names

[1] "sample_id"         "subject"           "age"
[4] "sex"               "nationality"       "bmi_group"
[7] "diversity_shannon"

In [18]:
meta |> select ( sex, starts_with "sam") |

ERROR: Error in parse(text = input): <text>:1:35: unexpected string constant
1: meta |> select ( sex, starts_with "sam"
                                      ^

---

## 3 · `mutate()` — add or change columns

`mutate()` creates new columns from existing ones. Every row is computed at once.

In [19]:
meta <- meta |>
  mutate(
    # cut() bins a numeric column into categories; 'breaks' are the cut points,
    # 'labels' name the 4 resulting age bands. Turns continuous age -> a factor.
    age_band = cut(age,
                   breaks = c(0, 30, 45, 60, 100),
                   labels = c("<30", "30-44", "45-59", "60+")),
    # A comparison makes a TRUE/FALSE column flagging high-diversity samples.
    high_diversity = diversity_shannon > 5.8
  )

# Show just the relevant columns to see the two new ones next to their source.
meta |> select(sample_id, age, age_band, diversity_shannon, high_diversity) |> head()

  sample_id age age_band diversity_shannon high_diversity
1 Sample-1  28  <30      5.76              FALSE
2 Sample-2  24  <30      6.06               TRUE
3 Sample-3  52  45-59    5.50              FALSE
4 Sample-4  22  <30      5.87               TRUE
5 Sample-5  25  <30      5.89               TRUE
6 Sample-6  42  30-44    5.53              FALSE

`stringr` helps when a column is **text**. Here we make a tidy, lower-case region
label and a short code:

In [22]:
meta <- meta |>
  mutate(
    # str_replace_all() swaps text using a named vector of "old" = "new" rules.
    region_label = str_replace_all(nationality, c("UKIE" = "UK & Ireland",
                                                   "US"   = "United States")),
    # str_sub(x, 1, 3) takes characters 1-3; str_to_upper() upper-cases them.
    region_code  = str_sub(nationality, 1, 3) |> str_to_upper()  # e.g. "Scandinavia" -> "SCA"
  )

# distinct() drops duplicate rows so we see one example of each region label.
meta |> select(nationality, region_label, region_code) |> distinct() |> head()

  nationality   region_label  region_code
1 US            United States US
2 CentralEurope CentralEurope CEN
3 Scandinavia   Scandinavia   SCA
4 SouthEurope   SouthEurope   SOU
5 UKIE          UK & Ireland  UKI
6 NA            NA            NA

### Exercise 2

Add a column `diversity_z` giving each sample's Shannon diversity as a
**z-score** (subtract the mean, divide by the standard deviation). Then show the
5 samples with the highest `diversity_z`.
*Hint:* `mean(x)`, `sd(x)`, and `arrange(desc(...))` (next section).

<details><summary><b>Solution</b> (click to expand)</summary>


```r
meta |>
  mutate(diversity_z = (diversity_shannon - mean(diversity_shannon)) /
                        sd(diversity_shannon)) |>
  arrange(desc(diversity_z)) |>
  select(sample_id, diversity_shannon, diversity_z) |>
  head(5)
```
</details>

---

## 4 · `arrange()` — sort the rows

In [21]:
meta |> arrange(age) |> head(3)                      # sort ascending -> youngest first
meta |> arrange(desc(diversity_shannon)) |> head(3)  # desc() = descending -> most diverse first
meta |> arrange(nationality, desc(age)) |> head(3)   # sort by region, then oldest within region

  sample_id  subject_id age sex    nationality   bmi_group diversity_shannon
1 Sample-340 340        18  female CentralEurope lean      6.19
2 Sample-703 703        18  female SouthEurope   lean      5.29
3 Sample-291 291        19  male   CentralEurope lean      5.44
  age_band high_diversity region_label  region_code
1 <30       TRUE          CentralEurope CEN
2 <30      FALSE          SouthEurope   SOU
3 <30      FALSE          CentralEurope CEN

  sample_id  subject_id age sex  nationality   bmi_group diversity_shannon
1 Sample-284 284        21  male CentralEurope lean      6.28
2 Sample-805 805        34  male Scandinavia   lean      6.28
3 Sample-404 404        26  male SouthEurope   lean      6.27
  age_band high_diversity region_label  region_code
1 <30      TRUE           CentralEurope CEN
2 30-44    TRUE           Scandinavia   SCA
3 <30      TRUE           SouthEurope   SOU

  sample_id  subject_id age sex    nationality   bmi_group  diversity_shannon
1 Sample-649 649        72  male   CentralEurope lean       5.95
2 Sample-674 674        72  female CentralEurope lean       6.07
3 Sample-320 320        71  female CentralEurope overweight 5.63
  age_band high_diversity region_label  region_code
1 60+       TRUE          CentralEurope CEN
2 60+       TRUE          CentralEurope CEN
3 60+      FALSE          CentralEurope CEN

---

## 5 · `group_by()` + `summarise()` — the core of analysis

This pattern answers almost every "…per group?" question. `group_by()` splits the
data into groups; `summarise()` collapses each group to one row of statistics.

In [ ]:
# group_by() tags the rows by nationality; summarise() then collapses each group to one row.
# (group_by must come first — summarise operates within whatever groups are set.)
meta |>
  group_by(nationality) |>
  summarise(
    n            = n(),                     # n() counts the rows (samples) in each group
    mean_shannon = mean(diversity_shannon), # average diversity for that region
    mean_age     = mean(age, na.rm = TRUE)  # average age; na.rm skips missing ages
  ) |>
  arrange(desc(mean_shannon))               # sort regions from most to least diverse

Group by **two** variables for a cross-tabulated summary:

In [ ]:
meta |>
  filter(!is.na(bmi_group)) |>                  # ignore samples with unknown BMI
  group_by(nationality, bmi_group) |>           # one group per region x BMI combination
  summarise(n = n(), .groups = "drop") |>       # count each combo; .groups="drop" ungroups after
  head(8)

> **Instructor note.** `summarise()` is where the biology appears: "mean
> diversity per region", "richness per BMI class". Emphasise the mental model of
> split, apply, combine.

### Exercise 3

For each `bmi_group` (excluding `NA`), report the number of samples and the
**median** Shannon diversity, sorted from most to least diverse.

<details><summary><b>Solution</b> (click to expand)</summary>


```r
meta |>
  filter(!is.na(bmi_group)) |>
  group_by(bmi_group) |>
  summarise(n = n(), median_shannon = median(diversity_shannon)) |>
  arrange(desc(median_shannon))
```
</details>

---

## 6 · Reshaping: `pivot_longer()` and `pivot_wider()`

Our abundance table is **wide** (130 genus columns). Most tidyverse tools — and
all of ggplot2 — prefer **long** (tidy) data: one row per *observation*. Here an
observation is "one genus in one sample".

In [ ]:
# pivot_longer stacks many columns into two: one for the old names, one for the values.
abund_long <- abund |>
  pivot_longer(
    cols      = -sample_id,   # pivot every column except sample_id (the '-' excludes it)
    names_to  = "genus",      # the old column names (genus names) fill this new column
    values_to = "abundance"   # the old cell values (counts) fill this new column
  )

abund_long          # tall table: 1006 samples x 130 genera = 130,780 rows, one per pair

Now every genus/sample pair is a row — perfect for joining, grouping and
plotting. To go back the other way, `pivot_wider()` spreads a long table wide:

In [ ]:
abund_long |>
  filter(genus %in% c("Akkermansia", "Escherichia coli et rel.")) |>  # just two genera
  # pivot_wider is the inverse: values from 'genus' become column names again.
  pivot_wider(names_from = genus, values_from = abundance) |>
  head()

> **Instructor note.** "Long for computing and plotting, wide for reading and
> matrices." This single idea covers most day-to-day omics wrangling.

---

## 7 · Joins — connecting tables

`abund_long` knows the *genus* but not its *phylum*. The `taxonomy` table has
that mapping. `left_join()` glues columns from `taxonomy` onto matching rows of
`abund_long`, matching on the shared `genus` column.

In [ ]:
# left_join keeps every row of the left table (abund_long) and pastes on matching
# taxonomy columns where the 'genus' key agrees.
abund_tax <- abund_long |>
  left_join(taxonomy, by = "genus")     # each row now also knows its phylum & family

abund_tax |> select(sample_id, genus, phylum, abundance) |> head()

Now join the **sample metadata** too, matching on `sample_id`, so every row knows
its participant's region and BMI group. This one tidy table combines all three
files:

In [ ]:
# Join the metadata too, matching on sample_id. We select() first so we only pull in
# the few metadata columns we need (not all 7) — keeps the joined table lean.
full <- abund_tax |>
  left_join(meta |> select(sample_id, nationality, bmi_group, age),
            by = "sample_id")

glimpse(full)      # every row = one genus, in one sample, with its taxonomy + participant info

> **Instructor note.** `left_join` keeps every row of the left table and adds
> matching info from the right. If a genus were missing from `taxonomy`, its
> `phylum` would be `NA`, which is a quick way to catch mismatches.

### Exercise 4

Using `abund_tax`, compute the **total abundance per phylum** across the whole
study, sorted from most to least abundant. Which phylum dominates the human gut
here?
*Hint:* `group_by(phylum)` then `summarise(total = sum(abundance))`.

<details><summary><b>Solution</b> (click to expand)</summary>


```r
abund_tax |>
  group_by(phylum) |>
  summarise(total = sum(abundance)) |>
  arrange(desc(total))
# Firmicutes and Bacteroidetes dominate — the classic gut signature.
```
</details>

---

## 8 · Putting it together — composition per region

Now we chain everything into one analysis: **the mean relative abundance of each
phylum, per geographic region.** This is the kind of multi-step pipe you will
write daily.

In [ ]:
composition <- full |>
  # 1. collapse the many genera into their phylum: total abundance per sample x phylum
  group_by(sample_id, nationality, phylum) |>
  summarise(phy_abund = sum(abundance), .groups = "drop") |>
  # 2. re-group by sample and divide by the sample's own total -> a proportion (0-1)
  group_by(sample_id) |>
  mutate(rel_abund = phy_abund / sum(phy_abund)) |>  # relative abundance within the sample
  ungroup() |>                                       # clear grouping before the next step
  # 3. now average those per-sample proportions across all samples of a region
  group_by(nationality, phylum) |>
  summarise(mean_rel = mean(rel_abund), .groups = "drop")

# Reshape to a human-readable table: one row per phylum, one column per region, in %.
composition |>
  mutate(mean_pct = round(mean_rel * 100, 1)) |>          # fraction -> rounded percentage
  select(phylum, nationality, mean_pct) |>
  pivot_wider(names_from = nationality, values_from = mean_pct)  # regions become columns

Read across a row to see how a phylum's share shifts between regions — a genuine
ecological pattern, produced with the six verbs plus a join and two pivots. We
**visualise** exactly this table in lesson 04.

In [ ]:
# Save for reuse / inspection.
saveRDS(composition, file.path(tempdir(), "composition.rds"))

### Exercise 5 (challenge)

Reorder the `phylum` factor by its **overall** mean relative abundance (most
abundant first) using `forcats::fct_reorder()`, then show the composition table
again. *Hint:* first compute an overall mean per phylum, or use `fct_reorder`
directly on the long `composition` with `mean_rel`.

<details><summary><b>Solution</b> (click to expand)</summary>


```r
composition |>
  mutate(phylum = fct_reorder(phylum, mean_rel, .fun = sum, .desc = TRUE)) |>
  arrange(phylum, nationality) |>
  head(10)
```
</details>

---

## Recap

- **`filter`** rows, **`select`** columns, **`mutate`** new columns,
  **`arrange`** to sort.
- **`group_by` + `summarise`** = split–apply–combine: the answer to every
  "per-group" question.
- **`pivot_longer` / `pivot_wider`** move between tidy-long and readable-wide.
- **`left_join`** connects tables on a shared key (`genus`, `sample_id`).
- **stringr** cleans text, **forcats** orders factors.
- Chaining these with the pipe turns three raw files into a real result:
  **phylum composition per region**.

**Next:** lesson **04** — turn these tables into figures with **ggplot2**.